# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "jbettiniS" do |master|
    master.vm.box = "generic/ubuntu1804"
    master.vm.hostname = "jbettiniS"
    master.vm.network "private_network", ip: "192.168.56.110"
    master.vm.synced_folder ".", "/vagrant", type: "nfs", nfs_version: 4, nfs_udp: false
    master.vm.provider :libvirt do |libvirt|
      libvirt.memory = 1024
      libvirt.cpus = 1
    end
    master.vm.provision "shell", path: "./scripts/bootMaster.sh"
  end

end

# #CMD interressante : ssh vagrant@localhost -p 2222 -i .vagrant/machines/"machineName"/virtualbox/private_key