# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|

  config.vm.define "jbettiniS" do |master|
    master.vm.box = "generic/ubuntu1804"
    master.vm.hostname = "jbettiniS"
    master.vm.network "private_network", ip: "192.168.56.110"
    master.vm.synced_folder ".", "/vagrant", type: "nfs", nfs_version: 4, nfs_udp: false
    master.vm.provider :libvirt do |libvirt|
      libvirt.memory = 1024
      libvirt.cpus = 1
    end
    master.vm.provision "shell", path: "./scripts/bootMaster.sh"
  end

  config.vm.define "jbettiniSW" do |worker|
    worker.vm.box = "generic/ubuntu1804"
    worker.vm.hostname = "jbettiniSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.synced_folder ".", "/vagrant", type: "nfs", nfs_version: 4, nfs_udp: false
    worker.vm.provider :libvirt do |libvirt|
      libvirt.memory = 1024
      libvirt.cpus = 1
    end
    worker.vm.provision "shell", path: "./scripts/bootWorker.sh"
  end

end



# #CMD interressante : ssh vagrant@localhost -p 2222 -i .vagrant/machines/"machineName"/virtualbox/private_key



